CREATE TABLE IF NOT EXISTS scheduled_job (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL UNIQUE,
    description   TEXT,
    job_group     VARCHAR(255),
    last_run_time TIMESTAMP WITH TIME ZONE,
    next_run_time TIMESTAMP WITH TIME ZONE,
    active        BOOLEAN NOT NULL DEFAULT TRUE,
    status        VARCHAR(50) NOT NULL DEFAULT 'IDLE'
);

CREATE INDEX IF NOT EXISTS idx_scheduled_job_name ON scheduled_job (name);
CREATE INDEX IF NOT EXISTS idx_scheduled_job_job_group ON scheduled_job (job_group);
CREATE INDEX IF NOT EXISTS idx_scheduled_job_status ON scheduled_job (status);
